import Head from 'next/head'
import Header from '../components/Header/Header'
import Navbar from '../components/Navbar/Navbar'
import Results from '../components/Results/Results'
import requests from '../utils/requests'
export default function Home({ results }) {
  return (
    <div >
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://i.pinimg.com/originals/78/c9/1c/78c91c35402c8aa695572aa023569cd8.png" type="image/icon" />
      </Head>

      <Header />
      <Navbar />
      <Results results={results} />
    </div>
  )
}
export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`).then(res => {
    return res.json()
  })
  return {
    props: {
      results: request.results,
    }
  }
}